blueprint: file

title: Image

accept:
  type: image
  extension: jpg, png, jpeg
  mime: image/jpeg, image/png

columns:
  - width: 1/1
    sections:
      meta:
        type: fields
        fields:
          photoCredit:
            label: crédit photo
            type: text
            width: 1/2
          alt:
            label: alt
            type: text
            width: 1/2
