blueprint: page

title: Project

num: date

icon: 📖

status:
  draft:
    label: Brouillon
    text: L'article est toujours en mode brouillon. Elle ne peut être vue que par les éditeurs ayant accès au panneau.
  unlisted:
    label: En attente de publication
    text: L'article n'est pas encore publiée. L'équipe doit toujours donner le feu vert final pour la publier.
  listed:
    label: Publié
    text: L'article est répertoriée dans l'archive et en ligne.

columns:
  - width: 1/1
    fields:
      subtitle:
        type: text
        required: false
        label: Sous-titre

      arrayOfImagesCarousel:
        type: files
        required: false
        label: Cover
        help: Image de couverture
        extends: fields/imageOnlyOne

      introduction:
        label: Intro
        type: writer
        marks:
          - bold
          - italic
          - link
        nodes:
          - paragraph

  - width: 1/2
    fields:
      htmlContent:
        type: blocks
        label: Contenu
        fieldsets:
          - image
          - video
          - text
          - type: heading
            extends: blocks/heading
            fields:
              level:
                options:
                  - h2
                  - h3

      galleryProject:
        type: blocks
        label: Galerie
        fieldsets:
          - image
          - video
  - width: 1/2
    sections:
      meta:
        type: fields
        fields:
          date:
            required: false
            label: Date
            help: Si il n'y a pas de date, le projet sera affiché "Ongoing"
            type: date
            default: false
            display: YYYY-MM
          tags:
            required: true
            label: tags
            type: multiselect
            min: 1
            options:
              type: query
              query: site.find('liste-des-tags').childrenAndDrafts.template('tag')
              text: "{{ item.title }}"
              value: "{{ item.uuid }}"

