blueprint: site

options:
  changeTitle: true
  preview: https://mycustomdomain.com

columns:
  - width: 1/4
    sections:
      about:
        label: " "
        type: pages
        status: listed
        image: false
        templates: about
        layout: cards
        size: medium
      themeList:
        label: " "
        type: pages
        status: listed
        image: false
        templates: tags
        layout: cards
        size: medium

  - width: 1/3
    sections:
      projects:
        label: " "
        type: pages
        status: listed
        image:
          cover: false
          back: white
        templates: projects
        layout: cards
        size: huge

